chain_client:
  # 链ID
  chain_id: "trustchain"
  # 组织ID
  org_id: "public"
  # 客户端用户私钥路径
  user_key_file_path: "/Users/horatio/IdeaProjects/demo1/src/main/resources/crypto-config/public/user/client1/client1.tls.key"
  # 客户端用户证书路径
  user_crt_file_path: "/Users/horatio/IdeaProjects/demo1/src/main/resources/crypto-config/public/user/client1/client1.tls.crt"
  # 客户端用户交易签名私钥路径(若未设置，将使用user_key_file_path)
  user_sign_key_file_path: "/Users/horatio/IdeaProjects/demo1/src/main/resources/crypto-config/public/user/client1/client1.sign.key"
  # 客户端用户交易签名证书路径(若未设置，将使用user_crt_file_path)
  user_sign_crt_file_path: "/Users/horatio/IdeaProjects/demo1/src/main/resources/crypto-config/public/user/client1/client1.sign.crt"
  # 同步交易结果模式下，轮询获取交易结果时的最大轮询次数，删除此项或设为<=0则使用默认值 10
  retry_limit: 50
  # 同步交易结果模式下，每次轮询交易结果时的等待时间，单位：ms 删除此项或设为<=0则使用默认值 500
  retry_interval: 100

  nodes:
    - # 节点地址，格式为：IP:端口:连接数 Peer1
      node_addr: "192.168.8.140:20201"
      # 节点连接数
      conn_cnt: 10
      # RPC连接是否启用双向TLS认证
      enable_tls: true
      # 信任证书池路径
      trust_root_paths:
        - "/Users/horatio/IdeaProjects/demo1/src/main/resources/crypto-config/public/ca"
        - "/Users/horatio/IdeaProjects/demo1/src/main/resources/crypto-config/buaa/ca"
      # TLS hostname
      tls_host_name: "chainmaker.org"
    - # 节点地址，格式为：IP:端口:连接数 Peer2
      node_addr: "192.168.8.238:20201"
      # 节点连接数
      conn_cnt: 10
      # RPC连接是否启用双向TLS认证
      enable_tls: true
      # 信任证书池路径
      trust_root_paths:
        - "/Users/horatio/IdeaProjects/demo1/src/main/resources/crypto-config/public/ca"
        - "/Users/horatio/IdeaProjects/demo1/src/main/resources/crypto-config/buaa/ca"
      # TLS hostname
      tls_host_name: "chainmaker.org"
  archive:
    # 数据归档链外存储相关配置
    type: "mysql"
    dest: "root:123456:localhost:3306"
    secret_key: xxx
  rpc_client:
    max_receive_message_size: 100 # grpc客户端接收消息时，允许单条message大小的最大值(MB)